# Generated by Django 5.0.6 on 2024-06-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_profile_name_temppassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempPassword',
        ),
    ]
