# Generated by Django 5.0.6 on 2024-06-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productchangerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productchangerequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='productchangerequest',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
