# Generated by Django 5.0.6 on 2024-06-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_productchangerequest_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital')], default='digital', max_length=10),
        ),
    ]
