# Generated by Django 5.0.6 on 2024-06-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productchangerequest',
            name='categories',
            field=models.ManyToManyField(related_name='change_requests', to='product.category'),
        ),
        migrations.AddField(
            model_name='productchangerequest',
            name='information',
            field=models.ManyToManyField(blank=True, related_name='change_requests', to='product.information'),
        ),
    ]
