# Generated by Django 5.0.6 on 2024-06-16 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_shiping_options_alter_productchangerequest_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shiping_options',
            new_name='Shipping_options',
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opt_products', to='product.shipping_options'),
        ),
    ]
