# Generated by Django 5.0.6 on 2024-06-16 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_shiping_options_shipping_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_options',
        ),
        migrations.AddField(
            model_name='shipping_options',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_options', to='product.product'),
            preserve_default=False,
        ),
    ]
