# Generated by Django 5.0.6 on 2024-06-19 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_product_shipping_options_and_more'),
        ('vendor', '0002_alter_vendorimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping_options',
            name='create_datetime',
        ),
        migrations.RemoveField(
            model_name='shipping_options',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shipping_options',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='shipping_options',
            name='modify_datetime',
        ),
        migrations.RemoveField(
            model_name='shipping_options',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_options',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='product.shipping_options'),
        ),
        migrations.AddField(
            model_name='shipping_options',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_options', to='vendor.vendor'),
            preserve_default=False,
        ),
    ]
