# Generated by Django 5.0.6 on 2024-06-20 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_shipping_options_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('percent', 'percent'), ('value', 'value')], max_length=7)),
                ('expire_at', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('code', models.CharField(blank=True, max_length=25)),
                ('min_price', models.FloatField()),
                ('max_value', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupon_categories', to='product.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupon_products', to='product.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_coupons', to=settings.AUTH_USER_MODEL)),
                ('user_used', models.ManyToManyField(blank=True, related_name='used_coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
