# Generated by Django 5.0.6 on 2024-06-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='issued_by',
            field=models.CharField(choices=[('site', 'site'), ('vendor', 'vendor')], default='site', max_length=10),
        ),
    ]
