# Generated by Django 5.0.6 on 2024-06-20 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_message_create_datetime_message_is_active_and_more'),
        ('ticket', '0003_remove_ticket_content_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='order.order'),
        ),
    ]
