# Generated by Django 5.0.6 on 2024-06-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finalize_day',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('approved', 'Approved'), ('delayed', 'Delayed'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=20),
        ),
    ]
