# Generated by Django 5.0.6 on 2024-06-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_finalize_day_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-14 12:24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delete',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='modify_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
