# Generated by Django 5.0.6 on 2024-06-16 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_freeze_money'),
        ('product', '0013_remove_product_shipping_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='product.shipping_options'),
            preserve_default=False,
        ),
    ]
