# Generated by Django 5.0.6 on 2024-06-16 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_shipping_option'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('modify_datetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_delete', models.BooleanField(default=False, editable=False)),
                ('type', models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital')], max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, help_text='its not necessarily if your order is digital', max_length=255, null=True)),
                ('state', models.CharField(blank=True, help_text='its not necessarily if your order is digital', max_length=255, null=True)),
                ('country', models.CharField(blank=True, help_text='its not necessarily if your order is digital', max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, help_text='its not necessarily if your order is digital', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, help_text='its not necessarily if your order is digital', max_length=255, null=True)),
                ('email', models.CharField(blank=True, help_text='its not necessarily if your order is digital', max_length=255, null=True)),
                ('description', models.TextField()),
                ('authـinfo', models.TextField(blank=True, help_text='its not necessarily if your order is physical', null=True)),
                ('account_address', models.CharField(blank=True, help_text='its not necessarily if your order is physical', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
