# Generated by Django 5.0.6 on 2024-06-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_shipping_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping_details',
            old_name='authـinfo',
            new_name='auth_info',
        ),
    ]
