# Generated by Django 5.0.6 on 2024-06-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
    ]
