# Generated by Django 5.0.6 on 2024-06-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default='2000-11-11 11:11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_delete',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='message',
            name='modify_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
